name: chartee
description: Flutter chart library
version: 1.0.0
homepage: https://github.com/chargee-energy/chartee

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
