name: chartee
description: Chartee is a versatile library supporting line, bar, and area charts for Flutter applications. Easily visualize data with customizable styles.
version: 1.0.14
homepage: https://github.com/chargee-energy/chartee

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  chargee_lints: ^1.0.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
